prompt Drop Objects script
DROP PACKAGE MY_PACKAGE;
DROP TYPE APP#LOG_TYPE;
DROP PACKAGE APP#LOG_UTIL;
DROP PACKAGE APP#ENV_UTIL;
DROP PACKAGE APP#TYPES;
DROP SEQUENCE APP#LOG_SEQ_ID;
DROP TRIGGER APP#LOGS_BR_DIU;
DROP VIEW APP#LOGS_DAILY;
DROP VIEW APP#LOGS_HOURLY;
DROP TABLE APP#ENVIRONMENT cascade constraints;
DROP TABLE APP#LOGS cascade constraints;
prompt All Test Objects dropped
prompt Thank You
