ALTER TABLE DEV.PLANETS MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.MOONS MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_PAIR_VALUES MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_PTF_CT_ARRAYAGG MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_PTF_CT_ARRAYAGG_BACKUP MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_PTF_RT_ARRAYAGG MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_PTF_RT_ARRAYAGG_BACKUP MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_PTF_RT_OBJECTAGG MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_PTF_RT_OBJECTAGG_BACKUP MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_PTF_CT_FLAT MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_PTF_CT_FLAT_BACKUP MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_PTF_RT_FLAT MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_PTF_RT_FLAT_BACKUP MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_PF_OBJECTS MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_PF_OBJECTS_BACKUP MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_JSON_TABLE MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_JSON_TABLE_BACKUP MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_PTF_RT_XML MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_PTF_RT_XML_BACKUP MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_XML_TABLE MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_XML_TABLE_BACKUP MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_PIVOT MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_ITEMS_PIVOT_BACKUP MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_PAIR_VALUES_BACKUP MOVE TABLESPACE DEV_DATA
ALTER TABLE DEV.OA_DPC_TEST_RESULTS MOVE TABLESPACE DEV_DATA


PL/SQL procedure successfully completed.

